### PR TITLE
Added new you tube resources for web development

### PR DESCRIPTION
**Pull request by anushka9555**
Hi. I have done the work assigned to me. Can you please review it?

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Thanks for your contribution @anushka9555

**Review by DhanushNehru — APPROVED** [review]

**Comment by anushka9555** [comment]
Hi @DhanushNehru. Just a small query. Since you haven't added hacktoberfest-accepted label on my PR? Will it be counted as one?

**Comment by DhanushNehru** [comment]
Hi @anushka9555 added

**Comment by anushka9555** [comment]
Tysm :)

**Pull request merged**
