### PR TITLE
Added game

### PR DESCRIPTION
**Pull request by NaMiKA0305**
plzz merge my pr.

### CODE REVIEW

**Review by epicadidash — CHANGES_REQUESTED** [review]
Please attach or comment a screenshot of the result achieved.
Rest all are fine

**Comment by NaMiKA0305** [comment]
Ohk

**Comment by NaMiKA0305** [comment]
Screenshot (106)
Screenshot (105)

**Comment by NaMiKA0305** [comment]
i made those changes.

**Review by epicadidash — APPROVED** [review]
Approved and All set!!!
Great Job @NaMiKA0305 👏
Hope you will have a great day ahead 😊
Hope I will review your next PR soon !!
See ya till we meet again 😄

**Comment by NaMiKA0305** [comment]
hello sir,
    as you can see i sent you my next pr. which is a game. plzz add it

**Comment by epicadidash** [comment]
Where @NaMiKA0305 ??

**Comment by NaMiKA0305** [comment]
i sent you pr#148, have a look. and plzz add it

**Pull request merged**
