### PR TITLE
Mini-Calculator

### PR DESCRIPTION
**Pull request by Nandinics04**

### CODE REVIEW

**Comment by Nandinics04** [comment]
@DhanushNehru 
please review my pull request

**Comment by DhanushNehru** [comment]
Hi @Nandinics04 please update the main readme list of projects section

**Comment by Nandinics04** [comment]
@DhanushNehru 
I have updated my readme list..
tell me if any changes needed in this

**Comment by Nandinics04** [comment]
@DhanushNehru 
please review my pull request

**Comment by Nandinics04** [comment]
sir tell me if any additional functionalities required

**Review by DhanushNehru — APPROVED** [review]

**Pull request merged**
