### PR TITLE
Added Hangman game

### PR DESCRIPTION
**Pull request by deveshidwivedi**

### CODE REVIEW

**Review by epicadidash — APPROVED** [review]
Approve

**Comment by epicadidash** [comment]
Approved and All set!!!
Great Job @NaMiKA0305 👏
Hope you will have a great day ahead 😊
Hope I will review your next PR soon !!
See ya till we meet again 😄

**Comment by deveshidwivedi** [comment]
Thank you so much! Good day!

**Comment by NaMiKA0305** [comment]
i want to add an snake game here but it is showing some error can you help me sir.

**Pull request merged**
