### PR TITLE
docs: add free hosting website to the README.md file

### PR DESCRIPTION
**Pull request by Durgesh4993**
image

image

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@Swpn0neel Please check it

**Review by selemondev — CHANGES_REQUESTED** [review]
Thanks @Durgesh4993 for your contribution. Could you please make a minor change? I want you to remove [Hyperphp](http://hyperphp.com/) from the list since it doesn't use a secure protocol (https) 😄.

**Comment by Durgesh4993** [comment]
Ok

**Comment by Durgesh4993** [comment]
@selemondev now you can check

**Review by selemondev — APPROVED** [review]
Thanks @Durgesh4993 for implementing the changes that I requested 🔥.

**Pull request merged**
