### PR TITLE
QR code generator Added 

### PR DESCRIPTION
**Pull request by Anju-Narnolia**
#187 
 A scannable QR code generator Added

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Please add image or video as well for this QR generator @Anju-Narnolia

**Comment by Anju-Narnolia** [comment]
Capture

**Comment by Anju-Narnolia** [comment]
Capture

**Comment by Anju-Narnolia** [comment]
Please review my PR now

**Review by DhanushNehru — APPROVED** [review]

**Comment by DhanushNehru** [comment]
Thanks for your contribution @Anju-Narnolia

**Pull request merged**
