### PR TITLE
Added Scroll to top button

### PR DESCRIPTION
**Pull request by HarineMurugan**
No button initially

image

On scrolling to next sections - button is shown

image

Color changes on scroll

image

Navigated to top on click

image

### CODE REVIEW

**Comment by HarineMurugan** [comment]
For the issue - https://github.com/DhanushNehru/Ultimate-Web-Development-Resources/issues/145

**Review by epicadidash — APPROVED** [review]
Approved and All set!!!
Great Job @HarineMurugan 👏
Hope you will have a great day ahead 😊
Hope I will review your next PR soon !!
See ya till we meet again 😄

**Comment by HarineMurugan** [comment]
Hi @epicadidash 
This PR is still showing as not approved in hacktoberfest profile. Can you please help me in approving this with hacktoberfest-accepted label?

**Comment by HarineMurugan** [comment]
Hi @epicadidash
This PR is still showing as not approved in hacktoberfest profile. Can you please help me in approving this with hacktoberfest-accepted label?

**Pull request closed without merging**
