### PR TITLE
Added a resource for web development-

### PR DESCRIPTION
**Pull request by khushi2762**
Added a free resource to learn HTML and CSS and get a certification.

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Please resolve merge conflicts @khushi2762

**Comment by khushi2762** [comment]
> Please resolve merge conflicts @khushi2762

Please check if its resolved.

**Comment by DhanushNehru** [comment]
You can add a new division called youtube channels and add the following

**Comment by khushi2762** [comment]
> You can add a new division called youtube channels and add the following

Yes, but i added a website link and not youtube link

**Comment by khushi2762** [comment]
> You can add a new division called youtube channels and add the following

Hey, I added a youtube resource as well :)

**Pull request merged**
