### PR TITLE
Added Responsive Registration Form

### PR DESCRIPTION
**Pull request by xvisierra**
Added Responsive Registration Form using HTML, CSS and Javascript with visually appealing design .

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Please add image / video of your output @xvisierra

**Comment by xvisierra** [comment]
In which directory am i suppossed to add images and videos ?

**Comment by DhanushNehru** [comment]
You can add here in the replies @xvisierra

**Comment by xvisierra** [comment]
image

**Comment by xvisierra** [comment]
Review and merge pls

**Pull request closed without merging**
