### PR TITLE
Linear_Gradient_background_creater as a micro JS Project

### PR DESCRIPTION
**Pull request by 05hiteshbansal**
Summary
This project is a javascript based Product. It allows you to click a cell and make a random Linear Gradient at random degree with random colours . Also number of colours are also not specific so a user can generate linear-Gradient with any number of colours .

Screen Short

screenshort

### CODE REVIEW

**Comment by 05hiteshbansal** [comment]
@fahurox  please review my PR

**Comment by 05hiteshbansal** [comment]
@mattzeunert please review my PR

**Comment by DhanushNehru** [comment]
@05hiteshbansal please update the main readme projects section as well

**Comment by 05hiteshbansal** [comment]
@DhanushNehru  could you please tell me where could i find link of my  contribution link in main repository

**Comment by 05hiteshbansal** [comment]
I am not able to find the link of project to be able to add in Readme.MD

**Comment by selemondev** [comment]
> I am not able to find the link of project to be able to add in Readme.MD

Hey @05hiteshbansal just specify where your project is, for example: '../my-project'.

**Review by selemondev — COMMENTED** [review]
Thanks for the pull request @05hiteshbansal 😄. Could you please resolve this error that occurs when someone clicks on the change colour button: `script.js:16 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'writeText')
    at HTMLButtonElement.displayDate (script.js:16:27)` ?

**Comment by 05hiteshbansal** [comment]
I removed the lines that were causing trouble 
can you now please review

**Review by selemondev — APPROVED** [review]
Impressive 🔥. Thank you @05hiteshbansal for your pull request 😄.

**Comment by 05hiteshbansal** [comment]
thanks for your appreciation

**Comment by selemondev** [comment]
> thanks for your appreciation

You are welcome. Thanks as well for your collaboration 😄.

**Pull request merged**
