### PR TITLE
Update README.md 

### PR DESCRIPTION
**Pull request by SoulNikhar**
Added 2 more websites to  Free Hosting and Web design software's

### CODE REVIEW

**Comment by SoulNikhar** [comment]
@DhanushNehru  Please have a look. 
Is any more changes required???

**Review by DhanushNehru — APPROVED** [review]

**Comment by DhanushNehru** [comment]
Please resolve merge conflicts @SoulNikhar

**Comment by SoulNikhar** [comment]
> Please resolve merge conflicts @SoulNikhar

@DhanushNehru  Merge conflict is now solved.  Have a look.

**Comment by SoulNikhar** [comment]
@DhanushNehru  now u can merge it. 
If all is all right. Thank you

**Review by DhanushNehru — APPROVED** [review]

**Pull request merged**
