### PR TITLE
Add Weather App

### PR DESCRIPTION
**Pull request by pabitra0011**
In this pr I add a weather app that simply fetch weather form openweather Api and show according to user input city or current location.

solved #159 

Screenshorts - 
image
image

Please review and merge it.

### CODE REVIEW

**Review by epicadidash — APPROVED** [review]
Approved and All set!!!
Great Job @pabitra0011  👏
Hope you will have a great day ahead 😊
Hope I will review your next PR soon !!
See ya till we meet again 😄

**Comment by pabitra0011** [comment]
Thank you so much! @epicadidash  sir😊 for your positive feedback.
Have a fantastic day ahead too!
Looking forward to collaborating again in the future.

**Comment by DhanushNehru** [comment]
Weather app looks great. Thanks for your contribution @pabitra0011

**Comment by pabitra0011** [comment]
Thank you so much! @DhanushNehru sir.
I am grateful for the opportunity and Your positive feedback serves as a source of motivation.

**Pull request merged**
