### PR TITLE
Added code for QR code generated

### PR DESCRIPTION
**Pull request by Kedarnath-Rothe**
#Fixes issue #187
QR

### CODE REVIEW

**Comment by Kedarnath-Rothe** [comment]
@DhanushNehru  Please see my PR...

**Comment by Kedarnath-Rothe** [comment]
@DhanushNehru Please see my PR...

**Comment by Kedarnath-Rothe** [comment]
#Fixed issue #175 


https://github.com/DhanushNehru/Ultimate-Web-Development-Resources/assets/143418802/1a623a18-83d1-447b-a992-bfc1e8aa793f
Portfolio

**Comment by Kedarnath-Rothe** [comment]
@DhanushNehru  Please see my PR

**Review by DhanushNehru — APPROVED** [review]

**Pull request merged**
