### PR TITLE
Added countdown timer using html, css and js

### LINKED ISSUE #335: Adding CountDown timer
I can add a countdown timer using html css and javascript

### PR DESCRIPTION
**Pull request by khushminder270**
Fixes #335

### CODE REVIEW

**Review by selemondev — APPROVED** [review]
Thanks @khushminder270 for your pull request. Could you please put the timer in this format: Hours | Minutes | Seconds 😄 ?

**Comment by khushminder270** [comment]
@selemondev Done with changes as per review comments

**Review by selemondev — CHANGES_REQUESTED** [review]
There is still one problem @khushminder270 , you just changed the words and not the numeric values. Could you please fix that 😄?

**Review by selemondev — CHANGES_REQUESTED** [review]
There is still one more problem @khushminder270 , you just changed the words and not the numeric values. Could you please fix that 😄?

**Pull request closed without merging**
