### PR TITLE
Added Temperature converter

### LINKED ISSUE #316: Adding temperature convertor
I can add a temperature convertor built using HTML, CSS, and Javascript with a good UI.

### PR DESCRIPTION
**Pull request by DivyanshiNarang**
closes #316 

Added Temperature converter that can convert Celsius to Kelvin and Fahrenheit and vice-versa.

Screenshot 2023-10-02 212617

### CODE REVIEW

**Comment by DivyanshiNarang** [comment]
Hi @DhanushNehru could you please guide me on how to update the main readme, as before merging I don't have GitHub repository link for temperature converter.

**Comment by DivyanshiNarang** [comment]
Hi @selemondev, please review this PR.

**Review by selemondev — COMMENTED** [review]
Great job @DivyanshiNarang 🔥. I need you to correct something, the conversion of Celsius to Kelvin is: Celsius + 273.15 and not:  Celsius + 273.32. Could you please correct that 😄?

**Review by selemondev — APPROVED** [review]
That was quick @DivyanshiNarang 🤯. Great job 🚀.

**Comment by DivyanshiNarang** [comment]
Thank you @selemondev. 😄

**Pull request merged**
