### PR TITLE
ADDED NEW QUIZ FILE (HTML,CSS,JAVA)

### PR DESCRIPTION
**Pull request by AnshMeshram**
#110

### CODE REVIEW

**Review by AnshMeshram — COMMENTED** [review]
please approve my  quiz  file

**Comment by DhanushNehru** [comment]
Please add image or video of your project output @AnshMeshram

**Comment by AnshMeshram** [comment]
https://github.com/DhanushNehru/Ultimate-Web-Development-Resources/assets/141160800/352ac67c-fd43-4c58-bb66-bdc72eae5e56

this is the program output

**Comment by AnshMeshram** [comment]
plz approve my pull request....

**Review by Swpn0neel — APPROVED** [review]
LGTM!!

**Pull request merged**
