### PR TITLE
Changes Made in Buttons

### PR DESCRIPTION
**Pull request by Prince-2204**
I have made some changes in the Buttons of the web Page and added some additional effect.

### CODE REVIEW

**Review by epicadidash — CHANGES_REQUESTED** [review]
Please add a screenshot of the change you have done @Prince-2204

**Comment by Prince-2204** [comment]
https://imgur.com/7udeEZj
https://imgur.com/pxwtIE8
@epicadidash check this i have made changes here

**Comment by Prince-2204** [comment]
@epicadidash have you seen the screenshots ?

**Comment by epicadidash** [comment]
It's not showing @Prince-2204

**Comment by Prince-2204** [comment]
@epicadidash can you please suggest then how can i show it to you ?

**Pull request merged**
