### PR TITLE
update README.md (Added 3 Resources)

### PR DESCRIPTION
**Pull request by myselfprincee**
**Added a Website to learn Coding :)**

### CODE REVIEW

**Comment by myselfprincee** [comment]
@Swpn0neel  Please also take a look at these. Please Please...

**Comment by myselfprincee** [comment]
@DhanushNehru Please review My contributions. Please :)

**Review by Swpn0neel — APPROVED** [review]

**Comment by myselfprincee** [comment]
@Swpn0neel  I have also ADDED 2 MORE PR's please have a look. I am a new contributor therefore, I don't fully understand the github 😅

**Comment by Swpn0neel** [comment]
> @Swpn0neel  I have also ADDED 2 MORE PR's please have a look. I am a new contributor therefore, I don't fully understand the github 😅

Tag me in those PRs please.

**Comment by myselfprincee** [comment]
#444 & #440

**Comment by myselfprincee** [comment]
> #444 & #440
@Swpn0neel  These are the PR's

**Comment by Swpn0neel** [comment]
> > #444 & #440
> @Swpn0neel  These are the PR's
> 
> 

Done ✅

**Pull request merged**
