### PR TITLE
Create Aeroplan Game

### LINKED ISSUE #256: Add Aeroplane Game
**Description**
The Aeroplane Game is a fun and interactive web-based game where you control an aeroplane's flight. Your objective is to fly the aeroplane for as long as possible while maintaining control and skill. The game offers an exciting challenge for players to test their flying skills.

**Tech Stack**
- HTML
- CSS
- JavaScript

 👉 **[Live Demo](https://sm-aeroplane-game.netlify.app)**

### PR DESCRIPTION
**Pull request by DevanshKyada27**
Fixes #256 

Created a Aeroplan game using HTML and CSS.
Tried to create the game as same as possible.

Hope this solves the issue.

Screen shot:
image

Screen Recording:

https://github.com/DhanushNehru/Ultimate-Web-Development-Resources/assets/143169520/610f70c9-d14c-4fb7-86d6-f161bbd89ea3

Looking forward for merging the PR.

### CODE REVIEW

**Comment by DevanshKyada27** [comment]
Hey @DhanushNehru @Swpn0neel @selemondev if you liked the changes of the PR. Can you please merge it. :)

**Comment by DevanshKyada27** [comment]
Hey @Swpn0neel @selemondev can you please merge this PR. :)

**Comment by DevanshKyada27** [comment]
Hey @selemondev you can refer to this PR. Hoping forward for merging this PR.

**Comment by DhanushNehru** [comment]
Hi @DevanshKyada27 please update the main readme , list of projects section as well

**Comment by DevanshKyada27** [comment]
OK @DhanushNehru will do it soon :)

**Comment by DevanshKyada27** [comment]
Done @DhanushNehru can you please just review and merge it. :)

**Review by DhanushNehru — APPROVED** [review]

**Pull request merged**
