### PR TITLE
Qr_Code_Generator project added

### PR DESCRIPTION
**Pull request by dalalsoham**

### CODE REVIEW

**Review by epicadidash — DISMISSED** [review]
also share a link to working version of it @dalalsoham to make sure everything is right before I approve it .
Rest the code is okay

**Comment by dalalsoham** [comment]
i have a live link ... can i add it here?in this comment

**Comment by dalalsoham** [comment]
@epicadidash

**Comment by dalalsoham** [comment]
this is the link of that website --> https://qr-code-generator-lemon.vercel.app/

**Comment by epicadidash** [comment]
Okay it looks fine and works for me .
I approve and commit it .

**Review by epicadidash — APPROVED** [review]
It's all seems to be working and is approved for the merge .
Great job @dalalsoham .
 Hope you have a nice day ahead .

**Pull request merged**
