### PR TITLE
Clock Project

### PR DESCRIPTION
**Pull request by jeevanshib**
A perfect HTML, CSS, JavaScript  project for beginners to learn and boast up their confidence by adding this to their resume.
Screenshot 2023-10-03 at 1 02 48 AM

### CODE REVIEW

**Comment by jeevanshib** [comment]
https://github.com/DhanushNehru/Ultimate-Web-Development-Resources/pull/133
@DhanushNehru could you review my PR. Looking forward to your feedback.

**Comment by jeevanshib** [comment]
@DhanushNehru Can you please take a review of my PR & merge it under HACTOBERFEST 2023.

**Comment by epicadidash** [comment]
@jeevanshib Please don't ping more than once .

**Review by epicadidash — APPROVED** [review]
I see you have done a beautiful job @jeevanshib , may you continue to do so.
Everything seems fine to me .
I am approving this for merge .
Have a nice day ahead.

**Comment by DhanushNehru** [comment]
Thanks for your contribution @jeevanshib

**Comment by DhanushNehru** [comment]
Thanks for your contribution @jeevanshib , Looks great

**Pull request merged**
