### PR TITLE
Merge pull request #2 from DhanushNehru/main

### PR DESCRIPTION
**Pull request by khsh13**
updates

### CODE REVIEW

**Comment by epicadidash** [comment]
Please elaborate on what is this @khsh13

**Comment by khsh13** [comment]
The PR for updating the changes done in the main branch from main repository in my forked repo

**Review by epicadidash — APPROVED** [review]
approved

**Comment by epicadidash** [comment]
okay ,
 Thanks @khsh13 for quick reply . 
Its approved

**Pull request merged**
