### PR TITLE
Rock-Paper-Scissor Project Added

### PR DESCRIPTION
**Pull request by Shreyasb1015**
This is my Rock-Paper-Scissor Project made with HTML,Css and Javascript language. It is fun game where player will be competing with Computer.It uses local storage to store the result of win,loss or draw of Player.Css adds some cool effect to the web page making it visually appealing.

### CODE REVIEW

**Comment by selemondev** [comment]
Thanks @Shreyasb1015 for your pull request. @subhayudutta has already added a project similar to yours 😄. Could you maybe update the name of the project from Stone Paper Scissors game to Rock, Paper, Scissors game in the README.md file?

**Comment by Shreyasb1015** [comment]
should i rename my project name?

**Comment by selemondev** [comment]
> should i rename my project name?

Actually just rename your project to Rock-Paper-Scissors-Game-V2 and then I will merge it 😄.

**Comment by Shreyasb1015** [comment]
I have renamed my file.

**Comment by selemondev** [comment]
> I have renamed my file.
Could you also add your project to the README.md file 😄?

**Comment by selemondev** [comment]
> I have renamed my file.

Could you also add your project to the README.md file 😄?

**Comment by Shreyasb1015** [comment]
Done. I have added my project.

**Review by selemondev — APPROVED** [review]
Thanks @Shreyasb1015 for your contributions and for implementing the changes that I requested 🚀 .

**Comment by Shreyasb1015** [comment]
My pleasure!

**Pull request merged**
