### PR TITLE
Add Book Cricket Game

### LINKED ISSUE #395: book cricket game
With a simple click, you can generate a random number between 0 and 9. If the outcome is 0, your batter is out; if it's 1, 2, 3, 4, or 6, those runs will be added to the batting team's score.

### PR DESCRIPTION
**Pull request by Bratajit-03**
### Description:
Created Book Cricket Game that can generate a random number between 0 and 9. If the outcome is 0, your batter is out; if it's 1, 2, 3, 4, or 6, those runs will be added to the batting team's score

### Issue:
closes #395

### CODE REVIEW

**Comment by Bratajit-03** [comment]
@DhanushNehru sir, @selemondev sir, kindly review my PR and allow it to merge.

**Comment by DhanushNehru** [comment]
Please update the main readme list of projects section @Bratajit-03

**Comment by Bratajit-03** [comment]
@DhanushNehru sir, I have updated the main Readme file. kindly review this PR and merge it.

**Comment by Bratajit-03** [comment]
@DhanushNehru sir, I have updated the main Readme file. kindly review this PR and merge it.

**Comment by Bratajit-03** [comment]
@Swpn0neel sir, @DhanushNehru sir kindly review my PR please.

**Review by DhanushNehru — APPROVED** [review]

**Pull request merged**
