### PR TITLE
Added Online Restaurant Website

### PR DESCRIPTION
**Pull request by rittikadeb**
## Description

Added Online Restaurant Website- Issue #376 

## Tech Stack Used
* HTML  
* CSS
* JavaScript

## Screenshot
image

### CODE REVIEW

**Comment by rittikadeb** [comment]
@selemondev can you pls review it.

**Comment by rittikadeb** [comment]
@DhanushNehru pls review it!

**Review by DhanushNehru — APPROVED** [review]

**Comment by DhanushNehru** [comment]
Please resolve merge conflicts @rittikadeb

**Comment by rittikadeb** [comment]
@DhanushNehru, I have resolved the conflicts. Please review it.

**Comment by DhanushNehru** [comment]
Thanks for your contribution @rittikadeb

**Pull request merged**
