### PR TITLE
TicTacToe Game

### LINKED ISSUE #442: Add TicTacToe Game
I want to Add TicTacToe Game . Please assign this issue to me.

### PR DESCRIPTION
**Pull request by DevanshKyada27**
Fixes #442 

Created a TicTacToe game using HTML, CSS and JS.

Hope this solves the issue.

Looking forward for merging this PR.

Screenshot:
image

Screen Recording:

https://github.com/DhanushNehru/Ultimate-Web-Development-Resources/assets/143169520/e9d96df9-8b80-4d10-b23a-d122d0b045f6

### CODE REVIEW

**Review by selemondev — CHANGES_REQUESTED** [review]
Great job @DevanshKyada27 🔥. Could you please add your project to the README.md file so that I can go ahead and merge it 😄?

**Comment by DevanshKyada27** [comment]
Sure @selemondev would add it soon:)

**Comment by DevanshKyada27** [comment]
Hey @selemondev do I have to add the project in your readme file and create a PR for that?

**Comment by DevanshKyada27** [comment]
Hey @selemondev if you liked the changes can you please merge the PR. :)

**Review by Swpn0neel — APPROVED** [review]

**Pull request closed without merging**
